# Generated by Django 5.2.10 on 2026-03-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('Plastic', 'Plastic'), ('Paper', 'Paper'), ('Metal', 'Metal'), ('Organic', 'Organic')], max_length=20)),
                ('quantity', models.FloatField()),
                ('source', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Collected', 'Collected'), ('Recycled', 'Recycled'), ('Reused', 'Reused')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
