# Generated by Django 5.2.10 on 2026-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('producer', 'Producer'), ('consumer', 'Consumer')], max_length=10),
        ),
    ]
