# Generated by Django 5.2.12 on 2026-03-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0006_profile_bio_profile_phone_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
