# Generated by Django 5.2.12 on 2026-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteapp', '0007_wasterequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
